// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Industry industry
//
// swagger:model Industry
type Industry struct {

	// code
	Code string `json:"code,omitempty"`

	// sector
	// Required: true
	Sector *string `json:"sector"`

	// segment
	Segment string `json:"segment,omitempty"`
}

// Validate validates this industry
func (m *Industry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Industry) validateSector(formats strfmt.Registry) error {

	if err := validate.Required("sector", "body", m.Sector); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Industry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Industry) UnmarshalBinary(b []byte) error {
	var res Industry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
