// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NaturalQuantity natural quantity
//
// swagger:model NaturalQuantity
type NaturalQuantity struct {

	// unit
	// Required: true
	Unit *string `json:"unit"`

	// value
	// Required: true
	// Maximum: 2.147483647e+09
	// Minimum: 0
	Value *float64 `json:"value"`
}

// Validate validates this natural quantity
func (m *NaturalQuantity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUnit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NaturalQuantity) validateUnit(formats strfmt.Registry) error {

	if err := validate.Required("unit", "body", m.Unit); err != nil {
		return err
	}

	return nil
}

func (m *NaturalQuantity) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	if err := validate.Minimum("value", "body", float64(*m.Value), 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("value", "body", float64(*m.Value), 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NaturalQuantity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NaturalQuantity) UnmarshalBinary(b []byte) error {
	var res NaturalQuantity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
