// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaxonomyTerm taxonomy term
//
// swagger:model taxonomy.Term
type TaxonomyTerm struct {

	// name
	Name string `json:"name,omitempty"`

	// rank
	Rank string `json:"rank,omitempty"`

	// subterms
	Subterms TaxonomyTerms `json:"subterms,omitempty"`

	// taxon
	Taxon string `json:"taxon,omitempty"`
}

// Validate validates this taxonomy term
func (m *TaxonomyTerm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubterms(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaxonomyTerm) validateSubterms(formats strfmt.Registry) error {

	if swag.IsZero(m.Subterms) { // not required
		return nil
	}

	if err := m.Subterms.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("subterms")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaxonomyTerm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaxonomyTerm) UnmarshalBinary(b []byte) error {
	var res TaxonomyTerm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
