name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate rest models
        run: make rest/models/

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
